// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDbTPpjBEURxaP55oOxNFAYqbOPJ1YnTU',
    appId: '1:761407466733:web:fd47bb07da5bdc04bff0e4',
    messagingSenderId: '761407466733',
    projectId: 'erica-map-f1e45',
    authDomain: 'erica-map-f1e45.firebaseapp.com',
    storageBucket: 'erica-map-f1e45.appspot.com',
    measurementId: 'G-87B4Y3DZRG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIBXUMQtGRBDwkkOdXt-lETQBe4zCHbCE',
    appId: '1:761407466733:android:5acc4bad785dd28abff0e4',
    messagingSenderId: '761407466733',
    projectId: 'erica-map-f1e45',
    storageBucket: 'erica-map-f1e45.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCazOrTP-voMtm5xrZW9cv0xRtErMPEw0w',
    appId: '1:761407466733:ios:46e8c919e048a7eebff0e4',
    messagingSenderId: '761407466733',
    projectId: 'erica-map-f1e45',
    storageBucket: 'erica-map-f1e45.appspot.com',
    iosBundleId: 'com.example.ericaMap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCazOrTP-voMtm5xrZW9cv0xRtErMPEw0w',
    appId: '1:761407466733:ios:46e8c919e048a7eebff0e4',
    messagingSenderId: '761407466733',
    projectId: 'erica-map-f1e45',
    storageBucket: 'erica-map-f1e45.appspot.com',
    iosBundleId: 'com.example.ericaMap',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDbTPpjBEURxaP55oOxNFAYqbOPJ1YnTU',
    appId: '1:761407466733:web:8fa08a75156da8c3bff0e4',
    messagingSenderId: '761407466733',
    projectId: 'erica-map-f1e45',
    authDomain: 'erica-map-f1e45.firebaseapp.com',
    storageBucket: 'erica-map-f1e45.appspot.com',
    measurementId: 'G-4STBQHC6GL',
  );
}
